Version 1.8.1

diff --git a/myfreerman-1/myfreerman b/myfreerman-1/myfreerman
--- a/myfreerman-1/myfreerman
+++ b/myfreerman-1/myfreerman
@@ -1,5 +1,5 @@
 #!/bin/bash
-RELEASE=1.8.0
+RELEASE=1.8.1
 
 function backup()
 {
@@ -117,14 +117,19 @@ function backup_binlog()
 	LIST=`head -n $COUNT $LIST_FILE`
 	LAST_BINLOG=`tail -n 1 $LIST_FILE`
 	rm $LIST_FILE
+	ERR_LOG=`mktemp /tmp/myfreerman.XXXXXX`
 	for BINLOG in $LIST; do
 		if ! [ -f "$BINLOG_BACKUP_DIR/${BINLOG}.gz" ]; then
 			LONG_LOGSEQ=`echo $BINLOG | cut -d . -f 2`
 			LOGSEQ=`expr $LONG_LOGSEQ + 0`
 			write_out "Saving binary log #${LOGSEQ}"
-			gzip -c9 "$BINLOG_DIR/$BINLOG" >"$BINLOG_BACKUP_DIR/${BINLOG}.gz" || { remove_lock_file && return 1; }
+			gzip -c9 "$BINLOG_DIR/$BINLOG" >"$BINLOG_BACKUP_DIR/${BINLOG}.gz" 2>$ERR_LOG
+			RC=$?
+			write_file_out $ERR_LOG
+			[ $RC -eq 0 ] || { rm $ERR_LOG; remove_lock_file; return 1; }
 		fi
 	done
+	rm $ERR_LOG
 	check_purge_binlogs $LAST_BINLOG || { remove_lock_file && return 1; }
 	remove_lock_file
 }
@@ -377,9 +382,12 @@ function help_list()
 function help_list_events
 {
 	echo "* List events in binary logs"
-	echo "   list events -t <threads> <min>"
-	echo "      Lists events generated in the last <min> minutes"
-	echo "      Output contains the following colums: binlog sequence number, date, time, operation, manipulated table, packet size (Mb)"
+	echo "   list events [ -t <threads> ] [ -b <binlog> ] [ -m <min> ]"
+	echo "      Output table contains the following colums: binlog sequence number, date, time, operation, manipulated table, packet size (Mb)"
+	echo "      -b: List events in binlog file <binlog>"
+	echo "         Cannot be used with -m"
+	echo "      -m: List events generated by local server in the last <min> minutes"
+	echo "         Cannot be used with -b"
 	echo "      -t: Use <threads> parallel processes to process logs"
 	echo "         min: 1, max: 50, default: 1"
 }
@@ -1671,8 +1679,7 @@ function list_binlog()
 function list_backup_events()
 {
 	MIN_DATE="$1"
-	OUTPUT1="$2"
-	OUTPUT2="$3"
+	OUTPUT="$2"
 	#if backup binlog dir doesn't exist, list empty
 	if ! [ -d "$BINLOG_BACKUP_DIR" ]; then
 		return
@@ -1685,7 +1692,7 @@ function list_backup_events()
 			SEQ=`echo $F | cut -d . -f 2`
 			BINLOG=`mktemp /tmp/myfreerman.XXXXXX.${SEQ}`
 			gunzip -c "$FPATH" >$BINLOG || { rm $BINLOG; return 1; }
-			list_one_binlog_events "${BINLOG}" "$MIN_DATE" "$OUTPUT1"
+			list_one_binlog_events "${BINLOG}" "$MIN_DATE" "$OUTPUT"
 			RC=$?
 			rm $BINLOG
 			if [ $RC -eq 100 ]; then
@@ -1695,14 +1702,14 @@ function list_backup_events()
 		fi
 		#if it is plain binlog, just call function
 		if file "$FPATH" | grep -wi "mysql" >/dev/null; then
-			list_one_binlog_events "${FPATH}" "$MIN_DATE" "$OUTPUT1"
+			list_one_binlog_events "${FPATH}" "$MIN_DATE" "$OUTPUT"
 			if [ $? -eq 100 ]; then
 				break
 			fi
 			continue
 		fi
 		#unknown type
-		write_out "Unknown file type [$FPATH]"
+		write_out "Not a binary log file [$FPATH]"
 		return 1
 	done
 }
@@ -1715,9 +1722,14 @@ function list_binlog_remote()
 function list_events()
 {
 	THREADS=1
+	MINUTES=
 	local OPTIND l_opt
-	while getopts "t:" l_opt; do
+	while getopts "b:m:t:" l_opt; do
 		case $l_opt in
+			b)
+				BINLOG_FILE="$OPTARG";;
+			m)
+				MINUTES=$OPTARG;;
 			t)
 				THREADS=$OPTARG;;
 			\?)
@@ -1727,11 +1739,44 @@ function list_events()
 		esac
 	done
 	shift $((OPTIND-1))
-	if [ $# -ne 1 ]; then
+	if [ $# -ne 0 ]; then
 		help_list_events
 		return 1
 	fi
 
+	#if binlog specified, check if it exists
+	if [ -n "$BINLOG_FILE" ]; then
+		if ! [ -f "$BINLOG_FILE" ]; then
+			write_out "No such file [$BINLOG_FILE]"
+			return 1
+		fi
+#and check if it is really a binlog
+		if ! file "$BINLOG_FILE" | grep -wi replication >/dev/null; then
+			write_out "Not a binary log file [$BINLOG_FILE]"
+			return 1
+		fi
+	fi
+
+	#one of options -b or -m is required
+	if [ -z "$BINLOG_FILE" -a -z "$MINUTES" ]; then
+		write_out "Required option missing: -b or -m"
+		return 1
+	fi
+
+	#the folloing options cannot be used together: -b and -m
+	if [ -n "$MINUTES" -a -n "$BINLOG_FILE" ]; then
+		write_out "The folloing options cannot be used together: -b and -m"
+		return 1
+	fi
+
+	#if minutes informed, check it
+	if [ -n "$MINUTES" ]; then
+		if [ $MINUTES -le 0 ]; then
+			write_out "Invalid number of minutes"
+		fi
+		MIN_DATE=`date --date="-$MINUTES minutes" +"%F %T"`
+	fi
+		
 	#check threads
 	if [ $THREADS -eq 0 ]; then
 		write_out "Number of threads must be greater than 1"
@@ -1741,25 +1786,24 @@ function list_events()
 		write_out "Number of threads cannot be greater than 50"
 		return 1
 	fi
-	MINUTE_COUNT=$1
-	MIN_DATE=`date --date="-$MINUTE_COUNT minutes" +"%F %T"`
 
-	OUTPUT1=`mktemp /tmp/myfreerman.XXXXXX`
-	OUTPUT2=`mktemp /tmp/myfreerman.XXXXXX`
-	list_local_events "$MIN_DATE" $OUTPUT1 $OUTPUT2
-	if [ $? -ne 100 ]; then
-		list_backup_events "$MIN_DATE" $OUTPUT1 $OUTPUT2
+	OUTPUT=`mktemp /tmp/myfreerman.XXXXXX`
+	if [ -n "$BINLOG_FILE" ]; then
+		list_one_binlog_events "$BINLOG_FILE" "" "$OUTPUT"
+	else
+		list_local_events "$MIN_DATE" $OUTPUT
+		if [ $? -ne 100 ]; then
+			list_backup_events "$MIN_DATE" $OUTPUT
+		fi
 	fi
-	sort $OUTPUT1
-	sort $OUTPUT2
-	rm $OUTPUT1 $OUTPUT2
+	sort $OUTPUT
+	rm $OUTPUT
 }
 
 function list_local_events()
 {
 	MIN_DATE="$1"
-	OUTPUT1="$2"
-	OUTPUT2="$3"
+	OUTPUT="$2"
 
 	#check if server has binary logs
 	LOG_BIN=`get_server_config log_bin` || return 1
@@ -1781,7 +1825,7 @@ function list_local_events()
 	for i in `seq 1 $COUNT`; do
 		NAME=`tail -n $i $BINLOG_LIST | head -n 1`
 		FULL_NAME="${BINLOG_DIRECTORY}/${NAME}"
-		list_one_binlog_events "${FULL_NAME}" "$MIN_DATE" "$OUTPUT1"
+		list_one_binlog_events "${FULL_NAME}" "$MIN_DATE" "$OUTPUT"
 		if [ $? -eq 100 ]; then
 			rm $BINLOG_LIST
 			return 100
@@ -1828,25 +1872,20 @@ function list_one_binlog_events()
 
 	#sequence is the last 6 chars in binlog path
 	SEQ=${FULL_PATH:(-6)}
-	#create tmp file for sql
-	SQL=`mktemp /tmp/myfreerman.XXXXXX`
-	mysqlbinlog --start-datetime="$MIN_DATE" --result-file $SQL "$FULL_PATH" || return 1
 
-	#if last event in binlog is earlier than our min date, ignore this binlog and return specific code (100)
-	LAST_TS="`get_binlog_last_event_timestamp $SQL`"
-	if [[ "$LAST_TS" < "$MIN_DATE" ]]; then
-		rm $SQL
-		return 100
+	MARK_LIST=`mktemp /tmp/myfreerman.XXXXXX`
+	if [ -n "$MIN_DATE" ]; then
+		#list only marks
+		mysqlbinlog --start-datetime="$MIN_DATE" "$FULL_PATH" | grep -Ew 'Table_map|STMT_END_F' >$MARK_LIST
+	else
+		mysqlbinlog "$FULL_PATH" | grep -Ew 'Table_map|STMT_END_F' >$MARK_LIST
 	fi
 
-	#list only marks
-	MARK_LIST=`mktemp /tmp/myfreerman.XXXXXX`
-	grep -Ew 'Table_map|STMT_END_F' $SQL >$MARK_LIST
 	TOTAL_LINES=`wc -l $MARK_LIST | cut -d \  -f 1`
-#if no line, leave
+	#if mark list is empty, inform we are already before min date
 	if [ $TOTAL_LINES -eq 0 ]; then
 		rm $MARK_LIST
-		return
+		return 100
 	fi
 
 	#if thread count is greater than 50% of total lines, reduce it
@@ -1870,7 +1909,7 @@ function list_one_binlog_events()
 	done
 	wait
 
-	rm $SQL #$MARK_LIST
+	rm $MARK_LIST
 }
 
 function list_one_binlog_events_th()
@@ -2470,6 +2509,12 @@ function recover_slave()
 	#if binlog backup dir doesn't exist
 	if ! [ -d "$BINLOG_BACKUP_DIR" ]; then
 		write_out "No backup directory found"
+		return 1
+	fi
+
+	#check if server is running
+	if ! mysqladmin --socket="$SERVER_SOCKET" ping >/dev/null 2>&1; then
+		write_out "Server is not running"
 		return 1
 	fi
 
