config file is not required 	for example, in clusters with vip, oem agent runs on a third host 	and it must list backups remotely - no configuration required in target host

diff --git a/myfreerman-1/myfreerman b/myfreerman-1/myfreerman
--- a/myfreerman-1/myfreerman
+++ b/myfreerman-1/myfreerman
@@ -1,5 +1,5 @@
 #!/bin/bash
-RELEASE=1.4.16
+RELEASE=1.4.17
 
 function apply_binlog()
 {
@@ -19,6 +19,7 @@ function backup()
 		usage
 		return 1
 	fi
+	check_config_backup || return 1
 	if [ $READ_ONLY -eq 1 ]; then
 		write_out "Read-only mode is enabled in configuration"
 		return 1
@@ -224,16 +225,6 @@ function check_config()
 		fi
 	fi
 
-	#BACKUP_DIR
-	if [ -z "$BACKUP_DIR" ]; then
-		echo "Configuration 'backup_dir' is required" >&2
-		return 1
-	fi
-	if [ ! -d "$BACKUP_DIR" ]; then
-		echo "'$BACKUP_DIR': no such directory" >&2
-		return 1
-	fi
-
 	#LOG_DIR
 	#if -l option used, log_dir is required
 	if [ -n "$LOG_FILE_BASENAME" -a -z "$LOG_DIR" ]; then
@@ -247,12 +238,6 @@ function check_config()
 			echo "'$LOG_DIR': no such directory" >&2
 			return 1
 		fi
-	fi
-
-	#LOCK_FILE - required
-	if [ -z "$LOCK_FILE" ]; then
-		echo "Configuration 'lock_file' is required" >&2
-		return 1
 	fi
 
 	#READ_ONLY - must be 0 or 1
@@ -271,6 +256,40 @@ function check_config()
 	if [ $WRITE_THREADS -lt 1 -o $WRITE_THREADS -gt $MAX_WRITE_THREADS ]; then
 		echo "configuration WRITE_THREADS must be between 1 and $MAX_WRITE_THREADS" >&2
 		return 1
+	fi
+}
+
+function check_config_backup()
+{
+	#BACKUP_DIR
+	if [ -z "$BACKUP_DIR" ]; then
+		echo "Configuration 'backup_dir' is required" >&2
+		return 1
+	fi
+	if [ ! -d "$BACKUP_DIR" ]; then
+		echo "'$BACKUP_DIR': no such directory" >&2
+		return 1
+	fi
+
+	#LOCK_FILE - required
+	if [ -z "$LOCK_FILE" ]; then
+		echo "Configuration 'lock_file' is required" >&2
+		return 1
+	fi
+}
+
+function check_config_list()
+{
+	if [ -z "$LIST_REMOTE_HOST" ]; then
+		#BACKUP_DIR
+		if [ -z "$BACKUP_DIR" ]; then
+			echo "Configuration 'backup_dir' is required" >&2
+			return 1
+		fi
+		if [ ! -d "$BACKUP_DIR" ]; then
+			echo "'$BACKUP_DIR': no such directory" >&2
+			return 1
+		fi
 	fi
 }
 
@@ -969,7 +988,12 @@ function list()
 		esac
 	done
 	shift $((OPTIND-1))
+	if [ $# -ne 1 ]; then
+		usage
+		return 1
+	fi
 	CMD=$1
+	check_config_list || return 1
 	if [ -n "$LIST_REMOTE_HOST" ]; then
 		list_remote $CMD || return 1
 		return
@@ -1004,9 +1028,9 @@ function list_binlog()
 	done
 }
 
-function list_binlog_remote
+function list_binlog_remote()
 {
-	ssh -q -o "StrictHostKeyChecking=no" $LIST_REMOTE_HOST myfreerman -c /etc/myfreerman/${LIST_REMOTE_HOST}.conf list binlog
+	ssh -q -o "StrictHostKeyChecking=no" $LIST_REMOTE_HOST MYSQL_SID=$MYSQL_SID myfreerman -q list binlog
 }
 
 function list_full()
@@ -1023,12 +1047,12 @@ function list_full()
 	done
 }
 
-function list_full_remote
+function list_full_remote()
 {
-	ssh -q -o "StrictHostKeyChecking=no" $LIST_REMOTE_HOST myfreerman -c /etc/myfreerman/${LIST_REMOTE_HOST}.conf list full
+	ssh -q -o "StrictHostKeyChecking=no" $LIST_REMOTE_HOST MYSQL_SID=$MYSQL_SID myfreerman -q list full
 }
 
-function list_remote
+function list_remote()
 {
 	REMOTE_USER=`whoami`
 	REMOTE_INST=`echo $REMOTE_HOST | cut -d . -f 1`
@@ -1040,6 +1064,10 @@ function list_remote
 			;;
 		binlog)
 			list_binlog_remote || return 1
+			;;
+		*)
+			usage
+			return 1
 			;;
 	esac
 }
@@ -1260,9 +1288,11 @@ function read_config()
 		INI_SECTION=${INI_SECTION}@${MYSQL_SID}
 	fi
 
+	#config file is not required
+	#for example, in clusters with vip, oem agent runs on a third host
+	#and it must list backups remotely - no configuration required in target host
 	if ! [ -f "$CONFIG_FILE" ]; then
-		echo "'$CONFIG_FILE': file not found" >&2
-		return 1
+		return
 	fi
 
 	BACKUP_DIR="`crudini --get "$CONFIG_FILE" $INI_SECTION backup_dir 2>/dev/null`"
@@ -1771,13 +1801,17 @@ function run()
 {
 	CONFIG_FILE=/etc/my.cnf
 	LOG_FILE_BASENAME=
-	while getopts "l:c:" opt; do
+	QUIET=0
+	while getopts "l:c:q" opt; do
 		case $opt in
 			l)
 				LOG_FILE_BASENAME=`date "+$OPTARG"` || return 1
 				;;
 			c)
 				CONFIG_FILE="$OPTARG"
+				;;
+			q)
+				QUIET=1
 				;;
 			\?)
 				echo "Invalid option: -$OPTARG" >&2
@@ -1794,7 +1828,9 @@ function run()
 	if [ -n "$LOG_FILE_BASENAME" ]; then
 		LOG_FILE="${LOG_DIR}/$LOG_FILE_BASENAME"
 	fi
-	header
+	if [ $QUIET -eq 0 ]; then
+		header
+	fi
 	TARGET_CRED_OPT=`mount_target_credentials_opt` || return 1
 	MYHOST=`hostname`
 	BASE_BACKUP_DIR="$BACKUP_DIR/base"
@@ -1858,7 +1894,11 @@ function uncompress_backup()
 
 function usage()
 {
-	echo "Usage:  myfreerman [ -c <config file> ] [ -l <log file format> ] <command> [ <cmd options> ]"
+	echo "Usage:  myfreerman [ -c <config file> ] [ -l <log file format> ] [ -q ] <command> [ <cmd options> ]"
+	echo "- options:"
+	echo "   -c   use a specific config file"
+	echo "   -l   specify format for log file name"
+	echo "   -q   quiet mode - do not print release information"
 	echo "- command:"
 	echo "   init"
 	echo "   backup full|binlog"
