See rpm changelog

diff --git a/mytjrsrman-1/mytjrsrman b/mytjrsrman-1/mytjrsrman
--- a/mytjrsrman-1/mytjrsrman
+++ b/mytjrsrman-1/mytjrsrman
@@ -1,5 +1,5 @@
 #!/bin/bash
-RELEASE=1.3.19
+RELEASE=1.3.20
 
 function apply_binlog()
 {
@@ -190,7 +190,7 @@ function check_target_instance_config()
 		return 1
 	fi
 	mysqld --defaults-file="$TMP_CONF" --bind-address=127.0.0.1 &
-	sleep 3
+	sleep 15
 	SUCCESS=1
 	if ! [ -f "$PID_FILE" ]; then
 		SUCCESS=0
@@ -563,6 +563,98 @@ function kill_pid()
 	done
 }
 
+function init()
+{
+	#mysqld user
+	MYSQLD_USER="`crudini --get \"$MYSQL_CONF_FILE\" mysqld user 2>/dev/null`"
+
+	#datadir
+	DATADIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld datadir`" 2>/dev/null
+	if [ -n "$DATADIR" ]; then
+		mkdir -p "$DATADIR" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$DATADIR" || return 1
+		fi
+	fi
+
+	#redo
+	REDODIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld innodb_log_group_home_dir 2>/dev/null`"
+	if [ -n "$REDODIR" ]; then
+		mkdir -p "$REDODIR" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$REDODIR" || return 1
+		fi
+	fi
+
+	#undo
+	UNDODIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld innodb_undo_directory 2>/dev/null`"
+	if [ -n "$UNDODIR" ]; then
+		mkdir -p "$UNDODIR" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$UNDODIR" || return 1
+		fi
+	fi
+
+	#binlog index file
+	BINLOG_INDEX="`crudini --get \"$MYSQL_CONF_FILE\" mysqld log_bin_index 2>/dev/null`"
+	if [ -n "$BINLOG_INDEX" ]; then
+		DNAME="`dirname $BINLOG_INDEX`" || return 1
+		mkdir -p "$DNAME" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$DNAME" || return 1
+		fi
+	fi
+
+	#binlogs directory
+	BINLOG_PREFIX="`crudini --get \"$MYSQL_CONF_FILE\" mysqld log_bin 2>/dev/null`"
+	if [ -n "$BINLOG_PREFIX" ]; then
+		BINLOG_DIR="`dirname $BINLOG_PREFIX`" || return 1
+		mkdir -p "$BINLOG_DIR" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$BINLOG_DIR" || return 1
+		fi
+	fi
+
+	#secure files directory
+	SECURE_DIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld secure_file_priv 2>/dev/null`"
+	if [ -n "$SECURE_DIR" ]; then
+		mkdir -p "$SECURE_DIR" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$SECURE_DIR" || return 1
+			chmod 700 "$SECURE_DIR" || return 1
+		fi
+	fi
+
+	#tmp directory
+	TMP_DIRECTORY="`crudini --get \"$MYSQL_CONF_FILE\" mysqld tmpdir 2>/dev/null`"
+	if [ -n "$TMP_DIRECTORY" ]; then
+		mkdir -p "$TMP_DIRECTORY" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$TMP_DIRECTORY" || return 1
+		fi
+	fi
+
+	#slow query log file
+	SLOW_QUERY_LOG_FILE="`crudini --get \"$MYSQL_CONF_FILE\" mysqld slow_query_log_file 2>/dev/null`"
+	if [ -n "$SLOW_QUERY_LOG_FILE" ]; then
+		DNAME="`dirname $SLOW_QUERY_LOG_FILE`" || return 1
+		mkdir -p "$DNAME" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$DNAME" || return 1
+		fi
+	fi
+
+	#general log file
+	GENERAL_LOG_FILE="`crudini --get \"$MYSQL_CONF_FILE\" mysqld general_log_file 2>/dev/null`"
+	if [ -n "$GENERAL_LOG_FILE" ]; then
+		DNAME="`dirname $GENERAL_LOG_FILE`" || return 1
+		mkdir -p "$DNAME" || return 1
+		if [ -n "$MYSQLD_USER" ]; then
+			chown $MYSQLD_USER "$DNAME" || return 1
+		fi
+	fi
+}
+
 function list()
 {
 	LIST_REMOTE_HOST=
@@ -678,6 +770,13 @@ function mount_credentials_opt()
 	echo -n "$RESULT"
 }
 
+function mount_limit_memory_option()
+{
+	if [ -n "$MAX_MEM" ]; then
+		echo "--limit-memory=$MAX_MEM"
+	fi
+}
+
 function mount_target_credentials_opt()
 {
 	RESULT=
@@ -713,8 +812,8 @@ function mysql_start()
 	OPTS="--defaults-file=$CONFIG --bind-address=127.0.0.1 --console"
 	write_out "Starting server (${INST_TYPE})"
 	$CMD $OPTS & >"$LOG_ERROR" 2>&1
-	sleep 2
-	COUNT=2
+	sleep 5
+	COUNT=5
 	while [ $COUNT -lt $START_TIMEOUT ]; do
 		if tail -n 20 "$LOG_ERROR" | grep -iw "ready for connections" >/dev/null; then
 			return 0
@@ -765,14 +864,14 @@ function mysql_stop()
 {
 	CONFIG="$1"
 	INST_TYPE="$2"
-	STOP_TIMEOUT=20
+	STOP_TIMEOUT=30
 	PID_FILE="`crudini --get \"$CONFIG\" mysqld pid_file 2>/dev/null`"
 	LOG_ERROR="`crudini --get \"$CONFIG\" mysqld log_error 2>/dev/null`"
 	write_out "Stopping server (${INST_TYPE})"
 	PID=`cat "$PID_FILE"`
 	kill $PID
-	sleep 1
-	COUNT=1
+	sleep 3
+	COUNT=3
 	while [ $COUNT -lt $STOP_TIMEOUT ]; do
 		if ! kill -0 $PID 2>/dev/null; then
 			return 0
@@ -982,8 +1081,10 @@ function restore()
 	PITR=0
 	RESTORE_TABLE_LIST=
 	REQ_TIMESTAMP=`date +%Y-%m-%d_%H:%M:%S`
+	SLAVE=0
+	ANSWER_YES=0
 	local OPTIND l_opt
-	while getopts "np:d:t:x:" l_opt; do
+	while getopts "np:d:st:x:y" l_opt; do
 		case $l_opt in
 			d)
 				RESTORE_DB_OLD_NAME=${OPTARG}
@@ -997,17 +1098,26 @@ function restore()
 				ISO_REQ_TIMESTAMP=${OPTARG/_/ }
 				DIR=`find_base_backup "$ISO_REQ_TIMESTAMP"` || return 1
 				;;
+			s)
+				SLAVE=1
+				;;
 			t)
 				RESTORE_TABLE_LIST="$RESTORE_TABLE_LIST ${OPTARG}"
 				;;
 			x)
 				RESTORE_DB_NEW_NAME=${OPTARG}
 				;;
+			y)
+				ANSWER_YES=1
+				;;
 			\?)
 				echo "Invalid option: -$OPTARG" >&2
 				;;
 		esac
 	done
+	if ! confirm_operation; then
+		return 0
+	fi
 	restore_validate_options || return 1
 	if ! [ -f "$MYSQL_CONF_FILE" ]; then
 		write_out "Cannot find readable file '$MYSQL_CONF_FILE'"
@@ -1082,10 +1192,19 @@ function restore()
 		AUX_SOCKET_OPT="--socket=$AUX_SOCKET"
 	fi
 	check_new_db_name || return 1
+	write_out "Starting restore"
+	MODE=off
+	if [ $SLAVE -eq 1 ]; then
+		MODE=on
+	fi
+	write_out "Slave mode: $MODE"
 	if [ $USE_AUX_INSTANCE -eq 0 ]; then	
 		restore_target_instance $DIR || return 1
 	else 
 		restore_aux_instance $DIR || return 1
+	fi
+	if [ $SLAVE -eq 1 ]; then
+		return
 	fi
 	recover $DIR "$REQ_TIMESTAMP" "$CONFIG" || return 1
 	if [ -n "$RESTORE_DB_OLD_NAME" ]; then
@@ -1112,11 +1231,12 @@ function restore_aux_instance()
 	create_aux_config $DIR || return 1
 	rm -fr "$AUX_DATADIR/*" || return 1
 	mkdir -p $AUX_DATADIR || return 1
+	LIM_MEM_OPT=`mount_limit_memory_option`
 	write_out "===== STARTING mysqlbackup ====="
 	if [ $BG_MODE -eq 0 ]; then
-		mysqlbackup --defaults-file=$AUX_CONFIG --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR copy-back 2>&1 || return 1
+		mysqlbackup --defaults-file=$AUX_CONFIG --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR $LIM_MEM_OPT copy-back 2>&1 || return 1
 	else
-		mysqlbackup --defaults-file=$AUX_CONFIG --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR copy-back >>"$LOG_FILE" 2>&1 || return 1
+		mysqlbackup --defaults-file=$AUX_CONFIG --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR $LIM_MEM_OPT copy-back >>"$LOG_FILE" 2>&1 || return 1
 	fi
 	write_out "===== FINISHED mysqlbackup ===== "
 	chown -R mysql $AUX_DATADIR || return 1
@@ -1178,11 +1298,12 @@ function restore_target_instance()
 	fi
 	check_empty_target_database || return 1
 	check_target_instance_config || return 1
+	LIM_MEM_OPT=`mount_limit_memory_option`
 	write_out "===== STARTING mysqlbackup ====="
 	if [ $BG_MODE -eq 0 ]; then
-		mysqlbackup --defaults-file=$MYSQL_CONF_FILE --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR copy-back 2>&1 || return 1 
+		mysqlbackup --defaults-file=$MYSQL_CONF_FILE --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR $LIM_MEM_OPT copy-back 2>&1 || return 1 
 	else
-		mysqlbackup --defaults-file=$MYSQL_CONF_FILE --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR copy-back >>"$LOG_FILE" 2>&1 || return 1 
+		mysqlbackup --defaults-file=$MYSQL_CONF_FILE --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR $LIM_MEM_OPT copy-back >>"$LOG_FILE" 2>&1 || return 1 
 	fi
 	write_out "===== FINISHED mysqlbackup ====="
 	if [ -n "$MYSQLD_USER" ]; then
@@ -1325,11 +1446,22 @@ function backup_binlog()
 	#next
 	N="`head -n 2 \"$BINLOG_INDEX\" | tail -n 1`" || return 1
 	backup_one_binlog "$F" "$N" || return 
-	remove_old_backups || return 1
 }
 
 function backup_full()
 {
+	IGNORE_BINLOGS=0
+	while getopts "n" opt; do
+		case $opt in
+			n)
+				IGNORE_BINLOGS=1
+				;;
+			\?)
+				echo "Invalid option: -$OPTARG" >&2
+				;;
+		esac
+	done
+	shift $((OPTIND-1))
 	CRED_OPT=`mount_credentials_opt` || return 1
 	cd "$BACKUP_DIR" || return 1
 	mkdir -p "$BASE_BACKUP_DIR" || return 1
@@ -1339,11 +1471,12 @@ function backup_full()
 	DIRECTORY="${BASE_BACKUP_DIR}/${TIMESTAMP}"
 	mkdir -p "$DIRECTORY" || return 1
 	IMAGE_FILE="${BASE_BACKUP_DIR}/${TIMESTAMP}.dat"
+	LIM_MEM_OPT=`mount_limit_memory_option`
 	write_out "===== STARTING mysqlbackup ====="
 	if [ $BG_MODE -eq 0 ]; then
-		mysqlbackup --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" backup-and-apply-log 2>&1
+		mysqlbackup --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" $LIM_MEM_OPT backup-and-apply-log 2>&1
 	else
-		mysqlbackup --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" backup-and-apply-log >>"$LOG_FILE" 2>&1
+		mysqlbackup --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" $LIM_MEM_OPT backup-and-apply-log >>"$LOG_FILE" 2>&1
 	fi
 	RETCODE=$?
 	write_out "===== FINISHED mysqlbackup ====="
@@ -1354,8 +1487,15 @@ function backup_full()
 	fi
 	cd "$BASE_BACKUP_DIR" || return 1
 	LAST_BACKUP=`ls | tail -n 1` || return 1
+	write_out "Saving MySQL config file"
+	cp "$MYSQL_CONF_FILE" "$DIRECTORY/my.cnf" || return 1
+	write_out "Saving mytjrsrman config file"
+	cp "$CONFIG_FILE" "$DIRECTORY/mytjrsrman.conf" || return 1
 	fix_backup_timestamp $LAST_BACKUP || return 1
-	backup_binlog || return 1
+	if [ $IGNORE_BINLOGS -eq 0 ]; then
+		backup_binlog || return 1
+	fi
+	remove_old_backups || return 1
 }
 
 function backup_one_binlog()
@@ -1392,20 +1532,21 @@ function run()
 			fi
 			remove_lock_file
 			;;
+		init)
+			init || return 1
+			;;
 		list)
 			if ! list $*; then
 				return 1
 			fi
 			;;
 		restore)
-			if confirm_operation; then
-				check_lock_file || return 1
-				if ! restore $*; then
-					remove_lock_file
-					return 1
-				fi
+			check_lock_file || return 1
+			if ! restore $*; then
 				remove_lock_file
+				return 1
 			fi
+			remove_lock_file
 			;;
 		*)
 			usage
@@ -1459,9 +1600,10 @@ function uncompress_backup()
 function usage()
 {
 	echo "Usage:"
-	echo "mytjrsrman [-b] backup full|binlog"
-	echo "mytjrsrman [-b] [-y] <restore options> restore"
-	echo "mytjrsrman [-b] list [-h <hostname> [-P <port>]] full|binlog"
+	echo "mytjrsrman [-b] [ -c <config file> ] init"
+	echo "mytjrsrman [-b] [ -c <config file> ] backup full|binlog"
+	echo "mytjrsrman [-b] [ -c <config file> ] restore [ <restore options> ]"
+	echo "mytjrsrman [-b] [ -c <config file> ] list [-h <hostname> [-P <port>]] full|binlog"
 }
 
 function write_out()
@@ -1488,7 +1630,6 @@ if [ $# -lt 1 ]; then
 fi
 MAX_READ_THREADS=20
 MAX_WRITE_THREADS=20
-ANSWER_YES=0
 BG_MODE=0
 READ_THREADS=1
 WRITE_THREADS=1
@@ -1501,9 +1642,6 @@ while getopts "byc:" opt; do
 			;;
 		c)
 			CONFIG_FILE="$OPTARG"
-			;;
-		y)
-			ANSWER_YES=1
 			;;
 		\?)
 			echo "Invalid option: -$OPTARG" >&2
