Fixing restore routine

diff --git a/mytjrsrman-1/mytjrsrman b/mytjrsrman-1/mytjrsrman
--- a/mytjrsrman-1/mytjrsrman
+++ b/mytjrsrman-1/mytjrsrman
@@ -79,13 +79,29 @@ function check_depends()
 
 function check_empty_target_database()
 {
-	if [ -z "$BINLOG_MASK" ]; then
-		write_out "Binary logs disabled - aborting"
+	#datadir must be empty
+	if ls -d "$DATADIR"/* >/dev/null 2>&1; then
+		write_out "Data directory [$DATADIR] must be empty"
+		return 1
+	fi
+	if [ -n "$REDODIR" ]; then
+		if [ "${REDODIR:0:1}" != "/" ]; then
+			REDODIR="$DATADIR/$REDODIR"
+		fi
+		mkdir -p "$REDODIR" || return 1
+		if ls -d "$REDODIR"/* >/dev/null 2>&1; then
+			write_out "Redo directory [$REDODIR] must be empty"
+			return 1
+		fi
+	fi
+	if [ -n "$BINLOG_MASK" ] && ls "$BINLOG_MASK"* >/dev/null 2>&1; then
+		write_out "No binary logs [${BINLOG_MASK}*] might exist"
 		return 1
 	fi
 
-	if ls "$BINLOG_MASK"* >/dev/null 2>&1; then
-		write_out "Binary logs [$BINLOG_MASK] found - aborting"
+	#binlog index file must not exist
+	if [ -n "$BINLOG_INDEX" -a -f "$BINLOG_INDEX" >/dev/null 2>&1 ]; then
+		write_out "Binary log index [$BINLOG_INDEX] must not exist"
 		return 1
 	fi
 }
@@ -140,34 +156,43 @@ function check_new_db_name()
 function check_target_instance_config()
 {
 	write_out "Checking target instance configuration"
-	if ! which mysqld >/dev/null 2>&1; then
-		write_out "Cannot find mysqld executable"
+	LOG_ERROR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld log_error 2>/dev/null`"
+	if [ -z "$LOG_ERROR" ]; then
+		write_out "MySQL configuration mysqld:log_error cannot be empty"
 		return 1
 	fi
-	T_LOG_FILE=`mktemp /tmp/mysqld.XXXXXX.log` || return 1
-	T_PID_FILE=`mktemp /tmp/mysqld.XXXXXX.pid` || return 1
-	rm "$T_PID_FILE" || return 1
-	if ! mysqld --initialize --bind-address=127.0.0.1 --log-error="$T_LOG_FILE" --pid-file="$T_PID_FILE" >>"$T_LOG_FILE" 2>&1; then
-		write_out "Cannot check target instance configuration. Check server log in '$T_LOG_FILE'."
+	PID_FILE="`crudini --get \"$MYSQL_CONF_FILE\" mysqld pid_file 2>/dev/null`"
+	if [ -z "$PID_FILE" ]; then
+		write_out "MySQL configuration mysqld:pid_file cannot be empty"
+		return 1
 	fi
-	mysqld --bind-address=127.0.0.1 --log-error="$T_LOG_FILE" --pid-file="$T_PID_FILE" &
-	sleep 10
+	if ! which mysqld >/dev/null 2>&1; then
+		write_out "Cannot find 'mysqld' executable file"
+		return 1
+	fi
+	TMP_LOG=`mktemp /tmp/mysqld.XXXXXX.log` || return 1
+	if ! mysqld --defaults-file="$MYSQL_CONF_FILE" --initialize >>"$TMP_LOG" 2>&1; then
+		write_out "Cannot check target instance configuration. Check server output in '$TMP_LOG' and logs in '$LOG_ERROR'."
+		return 1
+	fi
+	mysqld --defaults-file="$MYSQL_CONF_FILE" --bind-address=127.0.0.1 &
+	sleep 3
 	SUCCESS=1
-	if ! [ -f "$T_PID_FILE" ]; then
+	if ! [ -f "$PID_FILE" ]; then
 		SUCCESS=0
 	else
-		PID=`cat "$T_PID_FILE"`
+		PID=`cat "$PID_FILE"`
 		if ! kill -0 $PID; then
 			SUCCESS=0
 		fi
 	fi
 	if [ $SUCCESS -eq 1 ]; then
-		if ! kill_pid "$T_PID_FILE"; then
-			write_out "Timeout reached waiting for target instance to shutdown. PID file: '$T_PID_FILE'. Log file: '$T_LOG_FILE'."
+		if ! kill_pid "$PID_FILE"; then
+			write_out "Timeout reached waiting for target instance to shutdown. PID file: '$PID_FILE'. Log file: '$LOG_ERROR'."
 			return 1
 		fi
 	else
-		write_out "Cannot check target instance configuration. Check server log in '$T_LOG_FILE'."
+		write_out "Cannot check target instance configuration. Check server logs in '$LOG_ERROR'."
 		drop_target_database
 		return 1
 	fi
@@ -282,7 +307,6 @@ function create_aux_config()
 	TARGET_BASEDIR=`mysql $CRED_OPT -e "show global variables like 'basedir'" | tail -n 1 | cut -f 2 -d$'\t'`
 	LC_MESSAGES_DIR=`mysql $CRED_OPT -e "show global variables like 'lc_messages_dir'" | tail -n 1 | cut -f 2 -d$'\t'`
 	echo "[mysqld]" >$AUX_CONFIG
-	echo "bind-address=$AUX_BIND_ADDRESS" >>$AUX_CONFIG
 	echo "datadir=$AUX_DATADIR" >>$AUX_CONFIG
 	echo "explicit_defaults_for_timestamp=1" >>$AUX_CONFIG
 	echo "innodb_buffer_pool_size=10M" >>$AUX_CONFIG
@@ -443,8 +467,8 @@ function get_binlog_path()
 	LOGSEQ=$1
 	LONG_LOGSEQ=`seq -f "%06g" $LOGSEQ $LOGSEQ`
 	BINLOG=binlog.$LONG_LOGSEQ
-	if [ -f "$binlog_dir/$BINLOG" ]; then
-		echo "$binlog_dir/$BINLOG"
+	if [ -f "$BINLOG_DIR/$BINLOG" ]; then
+		echo "$BINLOG_DIR/$BINLOG"
 		return
 	fi
 	if [ -f $BINLOG_BACKUP_DIR/$BINLOG ]; then
@@ -545,8 +569,8 @@ function kill_pid()
 	PID_FILE="$1"
 	PID=`cat "$PID_FILE"`
 	kill $PID
-	sleep 2
-	COUNT=2
+	sleep 1
+	COUNT=1
 	while kill -0 $PID 2>/dev/null; do
 		COUNT=$((COUNT + 1))
 		if [ $COUNT -ge $WAIT_TIMEOUT ]; then
@@ -642,11 +666,31 @@ function mount_aux_defaults_file_opt()
 
 function mysql_start()
 {
-	if [ $USE_AUX_INSTANCE -eq 1 ]; then
-		mysql_start_aux || return 1
-	else
-		mysql_start_target || return 1
+	CONFIG="$1"
+	LOG_ERROR="`crudini --get \"$CONFIG\" mysqld log_error 2>/dev/null`"
+	START_TIMEOUT=120
+	PID_FILE="`crudini --get \"$CONFIG\" mysqld pid_file 2>/dev/null`"
+	CMD="mysqld --defaults-file=\"$CONFIG\" --bind-address=127.0.0.1"
+	$CMD >/dev/null 2>&1 &
+	sleep 3
+	COUNT=3
+	while [ $COUNT -lt $START_TIMEOUT ]; do
+		if tail -n 20 "$LOG_ERROR" | grep -iw "ready for connections" >/dev/null; then
+			return 0
+		fi
+		if ! [ -f "$PID_FILE" ]; then
+			write_out "Cannot start server - check logs in '$LOG_ERROR'"
+			return 1
+		fi
+		sleep 1
+		COUNT=$((COUNT + 1))
+	done
+	if [ -f "$PID_FILE" ]; then
+		PID=`cat "$PID_FILE"`
+		kill $PID
 	fi
+	write_out "Timeout reached waiting for server to start. Please check server logs in '$LOG_ERROR'"
+	return 1
 }
 
 function mysql_start_aux()
@@ -655,11 +699,11 @@ function mysql_start_aux()
 	write_out "Starting aux instance"
 	CMD="mysqld --defaults-file=$AUX_CONFIG"
 	$CMD &
-	sleep 3
-	COUNT=3
+	sleep 2
+	COUNT=2
 	while [ $COUNT -lt $START_TIMEOUT ]; do
-		sleep 2
-		COUNT=`expr $COUNT + 2`
+		sleep 1
+		COUNT=`expr $COUNT + 1`
 		if [ -f $AUX_LOG_ERROR ] && grep -w "\\[ERROR\\]" $AUX_LOG_ERROR >/dev/null; then
 			if [ -f $AUX_PID_FILE ]; then
 				PID=`cat $AUX_PID_FILE`
@@ -680,38 +724,25 @@ function mysql_start_aux()
 	return 1
 }
 
-function mysql_start_target()
-{
-	write_out "Starting MySQL"
-	if [ -n "$XAG_INSTANCE_NAME" ]; then
-		agctl start mysql_server $XAG_INSTANCE_NAME || return 1
-		sleep 2
-	else
-		if rpm -q systemd >/dev/null 2>&1; then
-			systemctl start ${MYSQL_SERVICE}.service
-		else
-			service $MYSQL_SERVICE start || return 1
-		fi
-	fi
-}
-
 function mysql_stop()
 {
-	TS=`date +"%H:%M:%S"`
-	if [ $BG_MODE -eq 0 ]; then
-		echo "[$TS] Stopping MySQL"
-	else
-		echo "[$TS] Stopping MySQL " >>"$LOG_FILE"
-	fi
-	if [ -n "$XAG_INSTANCE_NAME" ]; then
-		agctl stop mysql_server $XAG_INSTANCE_NAME
-	else
-		if rpm -q systemd >/dev/null 2>&1; then
-			systemctl stop ${MYSQL_SERVICE}.service
-		else
-			service $MYSQL_SERVICE stop
+	CONFIG="$1"
+	STOP_TIMEOUT=20
+	PID_FILE="`crudini --get \"$CONFIG\" mysqld pid_file 2>/dev/null`"
+	LOG_ERROR="`crudini --get \"$CONFIG\" mysqld log_error 2>/dev/null`"
+	PID=`cat "$PID_FILE"`
+	kill $PID
+	sleep 1
+	COUNT=1
+	while [ $COUNT -lt $STOP_TIMEOUT ]; do
+		if ! kill -0 $PID; then
+			return 0
 		fi
-	fi
+		sleep 1
+		COUNT=`expr $COUNT + 1`
+	done
+	write_out "Timeout reached waiting server to stop. Check server logs [${LOG_ERROR}]."
+	return 1
 }
 
 function port_available()
@@ -815,6 +846,7 @@ function recover()
 {
 	BASE_BACKUP=$1
 	MY_REQ_TIMESTAMP=$2
+	CONFIG="$3"
 	REQ_TIMESTAMP="${2/_/ }"
 	CRED_OPT=`mount_credentials_opt` || return 1
 	TMP_SQL=`mktemp /tmp/recover.XXXXXX.sql`
@@ -839,9 +871,29 @@ function recover()
 		LOGSEQ=`expr $LOGSEQ + 1`
 	done
 	#apply logs
-	mysql_start || return 1
+	MSG="Starting server"
+	if [ $USE_AUX_INSTANCE -eq 1 ]; then
+		MSG="Starting server (aux)"
+	fi
+	write_out "$MSG"
+	mysql_start "$CONFIG" || return 1
 	write_out "Applying binary logs"
-	mysql --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT $AUX_SOCKET_OPT <$TMP_SQL || return 1
+	if ! mysql --defaults-file="$CONFIG" $CRED_OPT <$TMP_SQL; then
+		MSG="Stopping server"
+		if [ $USE_AUX_INSTANCE -eq 1 ]; then
+			MSG="Stopping server (aux)"
+		fi
+		write_out "$MSG"
+		mysql_stop "$CONFIG"
+		rm $TMP_SQL
+		return 1
+	fi
+	MSG="Stopping server"
+	if [ $USE_AUX_INSTANCE -eq 1 ]; then
+		MSG="Stopping server (aux)"
+	fi
+	write_out "$MSG"
+	mysql_stop "$CONFIG"
 	rm $TMP_SQL
 }
 
@@ -961,18 +1013,12 @@ function restore()
 		return 1
 	fi
 	DATADIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld datadir`" 2>/dev/null
-	if [ -z "$DATADIR" ]; then
-		write_out "Data directory configuration [mysqld:datadir] cannot be empty"
-		return 1
-	fi
-
 	REDODIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld innodb_log_group_home_dir 2>/dev/null`"
 	UNDODIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld innodb_undo_directory 2>/dev/null`"
 	BINLOG_INDEX="`crudini --get \"$MYSQL_CONF_FILE\" mysqld log_bin_index 2>/dev/null`"
 	BINLOG_MASK="`crudini --get \"$MYSQL_CONF_FILE\" mysqld log_bin 2>/dev/null`"
-	if [ -z "$BINLOG_MASK" ]; then
-		write_out "Binary logs path [mysqld:log_bin] cannot be empty"
-		return 1
+	if [ -n "$BINLOG_MASK" ]; then
+		BINLOG_DIR="`dirname $BINLOG_MASK`" || return 1
 	fi
 
 	#secure files directory
@@ -989,6 +1035,7 @@ function restore()
 		echo "Invalid database name '$RESTORE_DB_NEW_NAME'" >&2
 		return 1
 	fi
+	CONFIG="$MYSQL_CONF_FILE"
 	if [ $USE_AUX_INSTANCE -eq 1 ]; then
 		cd "$AUX_BASEDIR" || return 1
 		cd -
@@ -1007,11 +1054,11 @@ function restore()
 		chown mysql "$AUX_BASEDIR" || return 1
 		DB_COPY=1
 		AUX_CONFIG=/tmp/${BASENAME}.cnf
+		CONFIG="$AUX_CONFIG"
 		AUX_DATADIR="$AUX_BASEDIR/datadir"
 		AUX_LOG_ERROR="$AUX_BASEDIR/mysql.log"
 		AUX_PID_FILE="$AUX_BASEDIR/pid_file"
 		AUX_SOCKET="$AUX_BASEDIR/socket"
-		AUX_BIND_ADDRESS=127.0.0.1
 		AUX_PORT=`find_aux_port` || return 1
 		AUX_SOCKET_OPT="--socket=$AUX_SOCKET"
 	fi
@@ -1022,10 +1069,7 @@ function restore()
 	else 
 		restore_aux_instance $DIR || return 1
 	fi
-	if [ $DB_COPY -eq 0 ]; then
-		crudini --set "$MYSQL_CONF_FILE" mysqld read_only 1 || return 1
-	fi
-	recover $DIR "$REQ_TIMESTAMP" || return 1
+	recover $DIR "$REQ_TIMESTAMP" "$CONFIG" || return 1
 	if [ -n "$RESTORE_DB_OLD_NAME" ]; then
 		copy_recovered_db || return 1
 	fi
@@ -1062,27 +1106,13 @@ function restore_aux_instance()
 function restore_target_instance()
 {
 	DIR="$1"
+	MYSQLD_USER="`crudini --get \"$MYSQL_CONF_FILE\" mysqld user`" 2>/dev/null
 	#if server is running, abort
 	if mysqladmin ping >/dev/null 2>&1; then
 		write_out "MySQL is running - aborting"
 		return 1
 	fi
 	mkdir -p "$DATADIR" || return 1
-	#if datadir is not empty, abort
-	if ls -d "$DATADIR"/* >/dev/null 2>&1; then
-		write_out "Data directory is not empty - aborting"
-		return 1
-	fi
-	if [ -n "$REDODIR" ]; then
-		if [ "${REDODIR:0:1}" != "/" ]; then
-			REDODIR="$DATADIR/$REDODIR"
-		fi
-		mkdir -p "$REDODIR" || return 1
-		if ls -d "$REDODIR"/* >/dev/null 2>&1; then
-			write_out "Redo directory is not empty - aborting"
-			return 1
-		fi
-	fi
 	if [ -n "$UNDODIR" ]; then
 		if [ "${UNDODIR:0:1}" != "/" ]; then
 			UNDODIR="$DATADIR/$UNDODIR"
@@ -1108,13 +1138,16 @@ function restore_target_instance()
 	else
 		mysqlbackup --defaults-file=$MYSQL_CONF_FILE --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir=$DIR copy-back >>"$LOG_FILE" 2>&1 || return 1 
 	fi
-	write_out "===== FINISHED mysqlbackup ===== "
-	chown -R mysql $DATADIR || return 1
-	if [ -n "$REDODIR" ]; then
-		chown -R mysql $REDODIR || return 1
-	fi
-	if [ -n "$UNDODIR" ]; then
-		chown -R mysql $UNDODIR || return 1
+	write_out "===== FINISHED mysqlbackup ====="
+	if [ -n "$MYSQLD_USER" ]; then
+		write_out "Setting permissions"
+		chown -R $MYSQLD_USER "$DATADIR" || return 1
+		if [ -n "$REDODIR" ]; then
+			chown -R $MYSQLD_USER "$REDODIR" || return 1
+		fi
+		if [ -n "$UNDODIR" ]; then
+			chown -R $MYSQLD_USER "$UNDODIR" || return 1
+		fi
 	fi
 }
 
@@ -1185,7 +1218,7 @@ function backup()
 		write_out "Cannot find binary logs directory in MySQL configuration file. Check if '$MYSQL_CONF_FILE' has variable [mysqld]:log_bin."
 		return 1
 	fi
-	BINLOG_DIR="`dirname $BINLOG_MASK`" || return 1
+	BINLOG_DIR="`dirname \"$BINLOG_MASK\"`" || return 1
 	DATADIR="`crudini --get \"$MYSQL_CONF_FILE\" mysqld datadir`" || return 1
 	#get mysql service
 	MYSQL_SERVICE=`find_mysql_service`
@@ -1215,7 +1248,7 @@ function backup_binlog()
 	BINLOG_INDEX="`mysql $CRED_OPT -e \"select @@log_bin_index\" | column -t | tail -n 1`" || return 1
 	cd "$BACKUP_DIR" || return 1
 	mkdir -p "$BINLOG_BACKUP_DIR" || return 1
-	cd "$binlog_dir" || return 1
+	cd "$BINLOG_DIR" || return 1
 	#while there are more than one binlog
 	COUNT=`cat "$BINLOG_INDEX" | wc -l` || return 1
 	while [ $COUNT -gt 1 ]; do
@@ -1337,8 +1370,8 @@ function stop_aux_instance()
 	sleep 3
 	COUNT=3
 	while [ $COUNT -lt $STOP_TIMEOUT ]; do
-		sleep 2
-		COUNT=`expr $COUNT + 2`
+		sleep 1
+		COUNT=`expr $COUNT + 1`
 		if ! [ -f $AUX_PID_FILE ]; then
 			rm "$AUX_CONFIG"
 			rm -fr "$AUX_BASEDIR"
