Config is read from mysql's config

diff --git a/mytjrsrman-1/mytjrsrman b/mytjrsrman-1/mytjrsrman
--- a/mytjrsrman-1/mytjrsrman
+++ b/mytjrsrman-1/mytjrsrman
@@ -1,5 +1,5 @@
 #!/bin/bash
-RELEASE=1.4.1
+RELEASE=1.4.2
 
 function apply_binlog()
 {
@@ -21,6 +21,151 @@ function apply_binlog()
 	mysqladmin --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT flush-logs || return 1
 	CUR_BINLOG=`tail "$BINLOG_INDEX"` || return 1
 	BN="`basename \"$CUR_BINLOG\"`" || return 1
+}
+
+function backup()
+{
+	if [ $# -lt 1 ]; then
+		echo "Missing backup type" >&2
+		usage
+		return 1
+	fi
+	if [ $READ_ONLY -eq 1 ]; then
+		write_out "Read-only mode is enabled in configuration"
+		return 1
+	fi
+
+	CRED_OPT=`mount_target_credentials_opt "$MYSQL_CONF_FILE"`
+	if [ $BG_MODE -eq 1 ]; then
+		if ! mysqladmin --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT ping >/dev/null 2>&1; then
+			write_out "No MySQL server running - ignoring backup"
+			return
+		fi
+	fi
+	if ! which mysqlbackup >/dev/null 2>&1; then
+		write_out "Cannot find 'mysqlbackup' in PATH"
+		return 1
+	fi
+	BKP_TYPE=`echo $1 | awk '{print tolower($0)}'`
+	shift
+	BINLOG_BASENAME=`mysql $CRED_OPT -e "show variables like 'log_bin_basename'" | tail -n 1 | cut -f 2 -d$'\t'` || return 1
+	BINLOG_DIR="`dirname \"$BINLOG_BASENAME\"`" || return 1
+	DATADIR="`crudini --get \"$MYSQL_CONF_FILE\" $SERVER_INI_SECTION datadir`" || return 1
+	case $BKP_TYPE in
+		full)
+			backup_full $* || return 1
+			;;
+		binlog)
+			backup_binlog $* || return 1
+			;;
+		*)
+			echo "Invalid backup type '$BKP_TYPE'" >&2
+			usage
+			return 1
+			;;
+	esac
+}
+
+function backup_binlog()
+{
+	local OPTIND l_opt
+	while getopts "" opt; do
+		case $opt in
+			\?)
+				echo "Invalid option: -$OPTARG" >&2
+				usage
+				return 1
+				;;
+		esac
+	done
+	shift $((OPTIND-1))
+	if  [ $# -ne 0 ]; then
+		usage
+		return 1
+	fi
+	cd "$BACKUP_DIR" || return 1
+	if ! exist_base_backup; then
+		echo "No full backup was previously done" >&2
+		return 1
+	fi
+	CRED_OPT=`mount_target_credentials_opt "$MYSQL_CONF_FILE"`
+
+	#create binlog backup dir
+	mkdir -p "$BINLOG_BACKUP_DIR" || return 1
+
+	#flush logs
+	mysqladmin --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT flush-logs || return 1
+
+	#list binlogs, just ignoring the last one
+	LIST_FILE=`mktemp /tmp/mytjrsrman.XXXXXX` || return 1
+	mysql --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT -e "show binary logs\G" | grep -wi log_name | cut -d \  -f 3 >$LIST_FILE || return 1
+	TOTAL=`cat $LIST_FILE | wc -l` || return 1
+	COUNT=$((TOTAL - 1))
+	LIST=`head -n $COUNT $LIST_FILE`
+	LAST_BINLOG=`tail -n 1 $LIST_FILE`
+	rm $LIST_FILE
+	for BINLOG in $LIST; do
+		if ! [ -f "$BINLOG_BACKUP_DIR/${BINLOG}.gz" ]; then
+			LONG_LOGSEQ=`echo $BINLOG | cut -d . -f 2`
+			LOGSEQ=`expr $LONG_LOGSEQ + 0`
+			write_out "Saving binary log sequence $LOGSEQ"
+			gzip -c9 "$BINLOG_DIR/$BINLOG" >"$BINLOG_BACKUP_DIR/${BINLOG}.gz" || return 1
+		fi
+	done
+	check_purge_binlogs $LAST_BINLOG || return 1
+}
+
+function backup_full()
+{
+	local OPTIND l_opt
+	while getopts "" opt; do
+		case $opt in
+			\?)
+				echo "Invalid option: -$OPTARG" >&2
+				usage
+				return 1
+				;;
+		esac
+	done
+	shift $((OPTIND-1))
+	if  [ $# -ne 0 ]; then
+		usage
+		return 1
+	fi
+	CRED_OPT=`mount_target_credentials_opt "$MYSQL_CONF_FILE"` || return 1
+	cd "$BACKUP_DIR" || return 1
+	mkdir -p "$BASE_BACKUP_DIR" || return 1
+	DATE_VAL=`date +%Y-%m-%d`
+	TIME_VAL=`date +%H-%M-%S`
+	TIMESTAMP=${DATE_VAL}_${TIME_VAL}
+	DIRECTORY="${BASE_BACKUP_DIR}/${TIMESTAMP}"
+	mkdir -p "$DIRECTORY" || return 1
+	IMAGE_FILE="${BASE_BACKUP_DIR}/${TIMESTAMP}.dat"
+	LIM_MEM_OPT=`mount_limit_memory_option`
+	write_out "===== STARTING mysqlbackup ====="
+	if [ $BG_MODE -eq 0 ]; then
+		mysqlbackup --defaults-group-suffix=$MYSQL_DEFAULT_GROUP_SUFFIX --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" $LIM_MEM_OPT backup-and-apply-log 2>&1
+	else
+		mysqlbackup --defaults-group-suffix=$MYSQL_DEFAULT_GROUP_SUFFIX --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" $LIM_MEM_OPT backup-and-apply-log >>"$LOG_FILE" 2>&1
+	fi
+	RETCODE=$?
+	write_out "===== FINISHED mysqlbackup ====="
+	#check_backup_consistency
+	if [ $RETCODE -ne 0 ]; then
+		rm -fr "${DIRECTORY}"
+		return 1
+	fi
+	cd "$BASE_BACKUP_DIR" || return 1
+	LAST_BACKUP=`ls | tail -n 1` || return 1
+	write_out "Saving MySQL config file"
+	cp "$MYSQL_CONF_FILE" "$DIRECTORY/my.cnf" || return 1
+	write_out "Saving mytjrsrman config file"
+	cp "$CONFIG_FILE" "$DIRECTORY/mytjrsrman.conf" || return 1
+	fix_backup_timestamp $LAST_BACKUP || return 1
+	backup_binlog || return 1
+	if [ -n "$RETENTION_PERIOD" ]; then
+		remove_old_backups || return 1
+	fi
 }
 
 function binlog_backup_exists()
@@ -80,12 +225,53 @@ function check_backup_consistency()
 
 function check_config()
 {
-	if [ $READ_THREADS -lt 1 -o $READ_THREADS -gt $MAX_READ_THREADS ]; then
-		echo "READ_THREADS config must be between 1 and $MAX_READ_THREADS" >&2
+	#AUX_BASEDIR - if defined, must exist
+	if [ -n "$AUX_BASEDIR" ]; then
+		if ! [ -d "$AUX_BASEDIR" ]; then
+			echo "'$AUX_BASEDIR': no such directory" >&1
+			return 1
+		fi
+	fi
+
+	#BACKUP_DIR
+	if [ -z "$BACKUP_DIR" ]; then
+		echo "Configuration 'backup_dir' is required" >&2
 		return 1
 	fi
-	if [ $WRITE_THWRITES -lt 1 -o $WRITE_THWRITES -gt $MAX_WRITE_THWRITES ]; then
-		echo "WRITE_THREADS config must be between 1 and $MAX_WRITE_THREADS" >&2
+	if [ ! -d "$BACKUP_DIR" ]; then
+		echo "'$BACKUP_DIR': no such directory" >&2
+		return 1
+	fi
+
+	#LOG_DIR - if defined, must exist
+	if [ -n "$LOG_DIR" ]; then
+		if ! [ -d "$LOG_DIR" ]; then
+			echo "'$LOG_DIR': no such directory" >&1
+			return 1
+		fi
+	fi
+
+	#LOCK_FILE - required
+	if [ -z "$LOCK_FILE" ]; then
+		echo "Configuration 'lock_file' is required" >&2
+		return 1
+	fi
+
+	#READ_ONLY - must be 0 or 1
+	if [ $READ_ONLY -ne 0 -a $READ_ONLY -ne 1 ]; then
+		echo "Configuration 'read_only' must be 0 or 1" >&2
+		return 1
+	fi
+
+	#READ_THREADS
+	if [ $READ_THREADS -lt 1 -o $READ_THREADS -gt $MAX_READ_THREADS ]; then
+		echo "Configuration 'read_threads' must be between 1 and $MAX_READ_THREADS" >&2
+		return 1
+	fi
+
+	#WRITE_THREADS
+	if [ $WRITE_THREADS -lt 1 -o $WRITE_THREADS -gt $MAX_WRITE_THREADS ]; then
+		echo "configuration WRITE_THREADS must be between 1 and $MAX_WRITE_THREADS" >&2
 		return 1
 	fi
 }
@@ -1095,6 +1281,66 @@ function read_binlog()
 	fi
 }
 
+function read_config()
+{
+	#mount ini section
+	INI_SECTION=mytjrsrman
+	if [ -n "$MYSQL_SID" ]; then
+		INI_SECTION=${INI_SECTION}@${MYSQL_SID}
+	fi
+
+	if ! [ -f "$CONFIG_FILE" ]; then
+		echo "'$CONFIG_FILE': file not found" >&2
+		return 1
+	fi
+
+	BACKUP_DIR="`crudini --get "$CONFIG_FILE" $INI_SECTION backup_dir 2>/dev/null`"
+
+	AUX_BASEDIR="`crudini --get "$CONFIG_FILE" $INI_SECTION aux_basedir 2>/dev/null`"
+
+	DB_HOSTNAME="`crudini --get "$CONFIG_FILE" $INI_SECTION db_hostname 2>/dev/null`"
+	DB_PASSWORD="`crudini --get "$CONFIG_FILE" $INI_SECTION db_password 2>/dev/null`"
+	DB_USERNAME="`crudini --get "$CONFIG_FILE" $INI_SECTION db_username 2>/dev/null`"
+
+	#log directory
+	LOG_DIR="`crudini --get "$CONFIG_FILE" $INI_SECTION log_dir 2>/dev/null`"
+
+	#lock file
+	LOCK_FILE="`crudini --get "$CONFIG_FILE" $INI_SECTION lock_file 2>/dev/null`"
+
+	#max memory
+	MAX_MEM="`crudini --get "$CONFIG_FILE" $INI_SECTION max_mem 2>/dev/null`"
+
+	#read only
+	READ_ONLY="`crudini --get "$CONFIG_FILE" $INI_SECTION READ_ONLY 2>/dev/null`"
+	#default: 1
+	if [ -z "${READ_ONLY}" ]; then
+		READ_ONLY=1
+	fi
+
+	#read threads
+	READ_THREADS="`crudini --get "$CONFIG_FILE" $INI_SECTION read_threads 2>/dev/null`"
+	#default: 1
+	if [ -z "$READ_THREADS" ]; then
+		READ_THREADS=1
+	fi
+
+	#retention period
+	RETENTION_PERIOD="`crudini --get "$CONFIG_FILE" $INI_SECTION retention_period 2>/dev/null`"
+
+	#slave server
+	SLAVE_SERVER="`crudini --get "$CONFIG_FILE" $INI_SECTION slave_server 2>/dev/null`"
+
+	#write threads
+	WRITE_THREADS="`crudini --get "$CONFIG_FILE" $INI_SECTION write_threads 2>/dev/null`"
+	#default: 1
+	if [ -z "$WRITE_THREADS" ]; then
+		WRITE_THREADS=1
+	fi
+
+	check_config || return 1
+}
+
 function recover()
 {
 	BASE_BACKUP=$1
@@ -1524,156 +1770,14 @@ function restore_validate_tablenames()
 	done
 }
 
-function validate_config()
-{
-	#read-only
-	if [ "$READ_ONLY" != "0" -a "$READ_ONLY" != "1" ]; then
-		write_out "Invalid value for READ_ONLY configuration"
-		return 1
-	fi
-	check_log_config || return 1
-}
-
-function backup()
-{
-	if [ $READ_ONLY -eq 1 ]; then
-		write_out "Read-only mode is enabled in configuration"
-		return 1
-	fi
-
-	CRED_OPT=`mount_target_credentials_opt "$MYSQL_CONF_FILE"`
-	if [ $BG_MODE -eq 1 ]; then
-		if ! mysqladmin --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT ping >/dev/null 2>&1; then
-			write_out "No MySQL server running - ignoring backup"
-			return
-		fi
-	fi
-	if ! which mysqlbackup >/dev/null 2>&1; then
-		write_out "Cannot find 'mysqlbackup' in PATH"
-		return 1
-	fi
-	CMD=`echo $1 | awk '{print tolower($0)}'`
-	shift
-	BINLOG_BASENAME=`mysql $CRED_OPT -e "show variables like 'log_bin_basename'" | tail -n 1 | cut -f 2 -d$'\t'` || return 1
-	BINLOG_DIR="`dirname \"$BINLOG_BASENAME\"`" || return 1
-	DATADIR="`crudini --get \"$MYSQL_CONF_FILE\" $SERVER_INI_SECTION datadir`" || return 1
-	case $CMD in
-		full)
-			backup_full $* || return 1
-			;;
-		binlog)
-			backup_binlog $* || return 1
-			;;
-		*)
-			usage
-			return 1
-			;;
-	esac
-}
-
-function backup_binlog()
-{
-	local OPTIND l_opt
-	while getopts "" opt; do
-		case $opt in
-			\?)
-				echo "Invalid option: -$OPTARG" >&2
-				usage
-				return 1
-				;;
-		esac
-	done
-	shift $((OPTIND-1))
-	if  [ $# -ne 0 ]; then
-		usage
-		return 1
-	fi
-	cd "$BACKUP_DIR" || return 1
-	if ! exist_base_backup; then
-		echo "No full backup was previously done" >&2
-		return 1
-	fi
-	CRED_OPT=`mount_target_credentials_opt "$MYSQL_CONF_FILE"`
-
-	#create binlog backup dir
-	mkdir -p "$BINLOG_BACKUP_DIR" || return 1
-
-	#flush logs
-	mysqladmin --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT flush-logs || return 1
-
-	#list binlogs, just ignoring the last one
-	LIST_FILE=`mktemp /tmp/mytjrsrman.XXXXXX` || return 1
-	mysql --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT -e "show binary logs\G" | grep -wi log_name | cut -d \  -f 3 >$LIST_FILE || return 1
-	TOTAL=`cat $LIST_FILE | wc -l` || return 1
-	COUNT=$((TOTAL - 1))
-	LIST=`head -n $COUNT $LIST_FILE`
-	LAST_BINLOG=`tail -n 1 $LIST_FILE`
-	rm $LIST_FILE
-	for BINLOG in $LIST; do
-		if ! [ -f "$BINLOG_BACKUP_DIR/${BINLOG}.gz" ]; then
-			LONG_LOGSEQ=`echo $BINLOG | cut -d . -f 2`
-			LOGSEQ=`expr $LONG_LOGSEQ + 0`
-			write_out "Saving binary log sequence $LOGSEQ"
-			gzip -c9 "$BINLOG_DIR/$BINLOG" >"$BINLOG_BACKUP_DIR/${BINLOG}.gz" || return 1
-		fi
-	done
-	check_purge_binlogs $LAST_BINLOG || return 1
-}
-
-function backup_full()
-{
-	local OPTIND l_opt
-	while getopts "" opt; do
-		case $opt in
-			\?)
-				echo "Invalid option: -$OPTARG" >&2
-				usage
-				return 1
-				;;
-		esac
-	done
-	shift $((OPTIND-1))
-	if  [ $# -ne 0 ]; then
-		usage
-		return 1
-	fi
-	CRED_OPT=`mount_target_credentials_opt "$MYSQL_CONF_FILE"` || return 1
-	cd "$BACKUP_DIR" || return 1
-	mkdir -p "$BASE_BACKUP_DIR" || return 1
-	DATE_VAL=`date +%Y-%m-%d`
-	TIME_VAL=`date +%H-%M-%S`
-	TIMESTAMP=${DATE_VAL}_${TIME_VAL}
-	DIRECTORY="${BASE_BACKUP_DIR}/${TIMESTAMP}"
-	mkdir -p "$DIRECTORY" || return 1
-	IMAGE_FILE="${BASE_BACKUP_DIR}/${TIMESTAMP}.dat"
-	LIM_MEM_OPT=`mount_limit_memory_option`
-	write_out "===== STARTING mysqlbackup ====="
-	if [ $BG_MODE -eq 0 ]; then
-		mysqlbackup --defaults-group-suffix=$MYSQL_DEFAULT_GROUP_SUFFIX --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" $LIM_MEM_OPT backup-and-apply-log 2>&1
-	else
-		mysqlbackup --defaults-group-suffix=$MYSQL_DEFAULT_GROUP_SUFFIX --defaults-file="$MYSQL_CONF_FILE" $CRED_OPT --read-threads=$READ_THREADS --write-threads=$WRITE_THREADS --backup-dir="${DIRECTORY}" $LIM_MEM_OPT backup-and-apply-log >>"$LOG_FILE" 2>&1
-	fi
-	RETCODE=$?
-	write_out "===== FINISHED mysqlbackup ====="
-	#check_backup_consistency
-	if [ $RETCODE -ne 0 ]; then
-		rm -fr "${DIRECTORY}"
-		return 1
-	fi
-	cd "$BASE_BACKUP_DIR" || return 1
-	LAST_BACKUP=`ls | tail -n 1` || return 1
-	write_out "Saving MySQL config file"
-	cp "$MYSQL_CONF_FILE" "$DIRECTORY/my.cnf" || return 1
-	write_out "Saving mytjrsrman config file"
-	cp "$CONFIG_FILE" "$DIRECTORY/mytjrsrman.conf" || return 1
-	fix_backup_timestamp $LAST_BACKUP || return 1
-	backup_binlog || return 1
-	remove_old_backups || return 1
-}
-
 function run()
 {
-	validate_config || return 1
+	header
+	read_config || return 1
+	if [ $# -lt 1 ]; then
+		usage
+		return 1
+	fi
 	CMD=`echo $1 | awk '{print tolower($0)}'`
 	shift
 	USE_AUX_INSTANCE=0
@@ -1687,7 +1791,6 @@ function run()
 			query $* || return 1
 			;;
 		backup)
-			header
 			check_lock_file || return 1
 			if ! backup $*; then
 				remove_lock_file
@@ -1712,10 +1815,10 @@ function run()
 			remove_lock_file
 			;;
 		*)
-			usage
 			if [ -n "$CMD" ]; then
 				echo "Invalid command: $CMD" >&2
 			fi
+			usage
 			return 1
 			;;
 	esac
@@ -1803,20 +1906,17 @@ function write_out()
 if [ "$DEBUG" == "1" ]; then
 	set -x
 fi
+BG_MODE=0
 MYSQL_CONF_FILE=/etc/my.cnf
 NOW_EPOCH=`date +%s`
 DATE_VAL=`date +%Y-%m-%d`
 TIME_VAL=`date +%H:%M:%S`
-if [ $# -lt 1 ]; then
-	usage
-	exit
-fi
 MAX_READ_THREADS=20
 MAX_WRITE_THREADS=20
 BG_MODE=0
 READ_THREADS=1
 WRITE_THREADS=1
-CONFIG_FILE=/etc/mytjrsrman.conf
+CONFIG_FILE=/etc/my.cnf
 READ_ONLY=0
 while getopts "bc:" opt; do
 	case $opt in
@@ -1832,13 +1932,8 @@ while getopts "bc:" opt; do
 	esac
 done
 shift $((OPTIND-1))
-source "$CONFIG_FILE" || exit -1
 check_depends || exit -1
 #check mysql conf file
-if ! [ -f "$MYSQL_CONF_FILE" ]; then
-	echo "MySQL config '$MYSQL_CONF_FILE' does not exist or is not a file." >&2
-	exit -1
-fi
 MYHOST=`hostname`
 BASE_BACKUP_DIR="$BACKUP_DIR/base"
 BINLOG_BACKUP_DIR="$BACKUP_DIR/binlog"
