Removed warning in authentication, when creating databases. Restore config: do not print END report. When restoring with -o, do not require BACKUP_DIR config.

diff --git a/src/myfreerman b/src/myfreerman
--- a/src/myfreerman
+++ b/src/myfreerman
@@ -1780,8 +1780,7 @@ function init_database()
 	echo "update mysql.user set host = '%' where user = 'root' and host = 'localhost';" >>$SQL
 	echo "flush privileges;" >>$SQL
 	echo "grant resource_group_admin, backup_admin on *.* to root;" >>$SQL
-	TARGET_CRED_OPT=`mount_target_credentials_opt` || return 1
-	mysql --connect-expired-password --socket="$SOCKET" -u root "-p$PASSWORD" <$SQL
+	MYSQL_PWD="$PASSWORD" mysql --login-path=nopath_xx --connect-expired-password --socket="$SOCKET" -u root <$SQL || echo "If you got an authentication failure, remove password from mysql authentication database and run INIT again"
 	mysql_stop
 	rm $SQL
 	[ $REPORT_FINISHED -eq 0 ] || write_out "Finished"
@@ -2750,12 +2749,6 @@ function restore()
 		return 1
 	fi
 
-#backup dir is required
-	if [ -z "$BACKUP_DIR" ]; then
-		echo "Configuration 'backup_dir' is required" >&2
-		return 1
-	fi
-
 	BINLOG_BACKUP_DIR="$BACKUP_DIR/binlog"
 	BASE_BACKUP_DIR="$BACKUP_DIR/base"
 	TMP_BACKUP_DIR="$BACKUP_DIR/tmp"
@@ -2803,6 +2796,13 @@ function restore_config()
 		help_restore_config
 		return 1
 	fi
+	REPORT_FINISHED=0
+	#backup dir is required
+	if [ -z "$BACKUP_DIR" ]; then
+		echo "Configuration 'backup_dir' is required" >&2
+		return 1
+	fi
+
 	BASE_BACKUP_DIR="$BACKUP_DIR/base"
 	[ -d "$BASE_BACKUP_DIR" ] || { write_out "No backup found" && return 1; }
 	REQ_TIMESTAMP=
@@ -2865,6 +2865,12 @@ function restore_database()
 		help_restore_database
 		return 1
 	fi
+	#backup dir is required
+	if [ -z "$BACKUP_DIR" ]; then
+		echo "Configuration 'backup_dir' is required" >&2
+		return 1
+	fi
+
 	BINLOG_BACKUP_DIR="$BACKUP_DIR/binlog"
 	BASE_BACKUP_DIR="$BACKUP_DIR/base"
 	TMP_BACKUP_DIR="$BACKUP_DIR/tmp"
