LIST EVENTS: thread count comes from config, and added support to define max timestamp

diff --git a/src/myfreerman b/src/myfreerman
--- a/src/myfreerman
+++ b/src/myfreerman
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 set -e
-RELEASE=2.1.9
+RELEASE=2.1.10
 
 function backup()
 {
@@ -447,15 +447,23 @@ function help_list()
 function help_list_events
 {
 	echo "* List events in binary logs"
-	echo "   list events [ -b <binlog> ] [ -h ] [ -m <min> ] [ -t <threads> ]"
+	echo "   list events [ -b <binlog> ] [ -h ] [ -m <min> ] [ -s <timestamp> ] [ -e <timestamp> ]"
 	echo "      Output table contains the following colums: binlog sequence number, date, time, operation, manipulated table, packet size (Mb)"
+	echo "      Minimum params are -s or -m"
 	echo "      -b: List events in binlog file <binlog>"
-	echo "         Cannot be used with -m"
 	echo "      -h: Show this help"
 	echo "      -m: List events generated by local server in the last <min> minutes"
-	echo "         Cannot be used with -b"
-	echo "      -t: Use <threads> parallel processes to process logs"
-	echo "         min: 1, max: 50, default: 1"
+	echo "         Cannot be used with -s or -e"
+	echo "      -e: List events occurred before <timestamp>"
+   echo "     	   Require -s option"
+	echo "         Cannot be used with -m"
+   echo "     	   <timestmap>: hhmm | ddhhmm | MMddhhmm | yyyy-MM-dd_hh:mm:ss"
+   echo "            hh: hour, mm: minute, dd: day, MM: month, yyyy: year, ss: second"
+	echo "      -s: List events occurred after <timestamp>"
+	echo "         Cannot be used with -m"
+   echo "     	   <timestmap>: hhmm | ddhhmm | MMddhhmm | yyyy-MM-dd_hh:mm:ss"
+   echo "            hh: hour, mm: minute, dd: day, MM: month, yyyy: year, ss: second"
+
 }
 
 function binlog_backup_exists()
@@ -547,6 +555,12 @@ function check_config()
 	#READ_ONLY - must be 0 or 1
 	if [ "$READ_ONLY" != "0" -a "$READ_ONLY" != "1" ]; then
 		echo "Configuration 'read_only' must be 0 or 1" >&2
+		return 1
+	fi
+
+	#PROCESS_THREADS - must be 1 to 75
+	if [ $PROCESS_THREADS -lt 1 -o $PROCESS_THREADS -gt 75 ]; then
+		write_out "Configuration 'process_threads' must be between 1 and 75"
 		return 1
 	fi
 
@@ -1068,7 +1082,7 @@ function get_server_config()
 	CONFIG_NAME=$1
 	CMD="select @@${CONFIG_NAME}\G"
 	BUFF=`mktemp /tmp/myfreerman.XXXXXX`
-	mysql -N --socket="$SERVER_SOCKET" $TARGET_CRED_OPT -e "$CMD" >$BUFF || return 1
+	mysql -N --socket="$SERVER_SOCKET" $TARGET_CRED_OPT_NOPWD -e "$CMD" >$BUFF || { rm $BUFF; return 1; }
 	RC=$?
 	tail -n 1 $BUFF
 	rm $BUFF
@@ -1880,44 +1894,6 @@ function list_binlog()
 	done
 }
 
-function list_backup_events()
-{
-	MIN_DATE="$1"
-	OUTPUT="$2"
-	#if backup binlog dir doesn't exist, list empty
-	if ! [ -d "$BINLOG_BACKUP_DIR" ]; then
-		return
-	fi
-	LIST=`ls -r "$BINLOG_BACKUP_DIR"`
-	for F in $LIST; do
-		FPATH="$BINLOG_BACKUP_DIR/$F"
-		#if it is compressed, uncompress
-		if file "$FPATH" | grep -wi "compressed" >/dev/null; then
-			SEQ=`echo $F | cut -d . -f 2`
-			BINLOG=`mktemp /tmp/myfreerman.XXXXXX.${SEQ}`
-			gunzip -c "$FPATH" >$BINLOG || { rm $BINLOG; return 1; }
-			list_one_binlog_events "${BINLOG}" "$MIN_DATE" "$OUTPUT"
-			RC=$?
-			rm $BINLOG
-			if [ $RC -eq 100 ]; then
-				break
-			fi
-			continue
-		fi
-		#if it is plain binlog, just call function
-		if file "$FPATH" | grep -wi "mysql" >/dev/null; then
-			list_one_binlog_events "${FPATH}" "$MIN_DATE" "$OUTPUT"
-			if [ $? -eq 100 ]; then
-				break
-			fi
-			continue
-		fi
-		#unknown type
-		write_out "Not a binary log file [$FPATH]"
-		return 1
-	done
-}
-
 function list_binlog_remote()
 {
 	ssh -q -o "StrictHostKeyChecking=no" $LIST_REMOTE_HOST MYSQL_SID=$MYSQL_SID myfreerman -q list binlog
@@ -1925,11 +1901,12 @@ function list_binlog_remote()
 
 function list_events()
 {
-	THREADS=1
 	MINUTES=
 	DETAILED=0
+	START_TIME=
+	END_TIME=
 	local OPTIND l_opt
-	while getopts "b:dhm:t:" l_opt; do
+	while getopts "b:dhm:s:e:" l_opt; do
 		case $l_opt in
 			b)
 				BINLOG_FILE="$OPTARG";;
@@ -1941,8 +1918,10 @@ function list_events()
 				;;
 			m)
 				MINUTES=$OPTARG;;
-			t)
-				THREADS=$OPTARG;;
+			s)
+				START_TIME=$OPTARG;;
+			e)
+				END_TIME=$OPTARG;;
 			\?)
 				help_list_events
 				return 1
@@ -1954,99 +1933,7 @@ function list_events()
 		help_list_events
 		return 1
 	fi
-
-	#if binlog specified, check if it exists
-	if [ -n "$BINLOG_FILE" ]; then
-		if ! [ -f "$BINLOG_FILE" ]; then
-			write_out "No such file [$BINLOG_FILE]"
-			return 1
-		fi
-#and check if it is really a binlog
-		if ! file "$BINLOG_FILE" | grep -wi replication >/dev/null; then
-			write_out "Not a binary log file [$BINLOG_FILE]"
-			return 1
-		fi
-	fi
-
-	#one of options -b or -m is required
-	if [ -z "$BINLOG_FILE" -a -z "$MINUTES" ]; then
-		write_out "Required option missing: -b or -m"
-		return 1
-	fi
-
-	#the folloing options cannot be used together: -b and -m
-	if [ -n "$MINUTES" -a -n "$BINLOG_FILE" ]; then
-		write_out "The folloing options cannot be used together: -b and -m"
-		return 1
-	fi
-
-	#if minutes informed, check it
-	if [ -n "$MINUTES" ]; then
-		if [ $MINUTES -le 0 ]; then
-			write_out "Invalid number of minutes"
-		fi
-		MIN_DATE=`date --date="-$MINUTES minutes" +"%F %T"`
-	fi
-		
-	#check threads
-	if [ $THREADS -eq 0 ]; then
-		write_out "Number of threads must be greater than 1"
-		return 1
-	fi
-	if [ $THREADS -gt 50 ]; then
-		write_out "Number of threads cannot be greater than 50"
-		return 1
-	fi
-
-	OUTPUT=`mktemp /tmp/myfreerman.XXXXXX`
-	if [ -n "$BINLOG_FILE" ]; then
-		if [ $DETAILED -eq 1 ]; then
-			list_one_binlog_events_detailed "$BINLOG_FILE" "" "$OUTPUT"
-		else
-			list_one_binlog_events "$BINLOG_FILE" "" "$OUTPUT"
-		fi
-	else
-		list_local_events "$MIN_DATE" $OUTPUT
-		if [ $? -ne 100 ]; then
-			list_backup_events "$MIN_DATE" $OUTPUT
-		fi
-	fi
-	sort $OUTPUT
-	rm $OUTPUT
-}
-
-function list_local_events()
-{
-	MIN_DATE="$1"
-	OUTPUT="$2"
-
-	#check if server has binary logs
-	LOG_BIN=`get_server_config log_bin` || return 1
-	if [ $LOG_BIN -eq 0 ]; then
-		write_out "Logging is disbled in server"
-		return 1
-	fi
-
-	#binlog directory
-	LOG_BIN_BASENAME=`mysql --socket="$SERVER_SOCKET" $TARGET_CRED_OPT -e "show variables like 'log_bin_basename'" | tail -n 1 | cut -f 2 -d$'\t'` || return 1
-	BINLOG_DIRECTORY="`dirname \"$LOG_BIN_BASENAME\"`"
-
-	#list binlogs
-	BINLOG_LIST=`mktemp /tmp/myfreerman.XXXXXX`
-	list_server_binlogs >$BINLOG_LIST || return 1
-
-	#for each binlog, from last to first
-	COUNT=`wc -l $BINLOG_LIST | cut -d \  -f 1`
-	for i in `seq 1 $COUNT`; do
-		NAME=`tail -n $i $BINLOG_LIST | head -n 1`
-		FULL_NAME="${BINLOG_DIRECTORY}/${NAME}"
-		list_one_binlog_events "${FULL_NAME}" "$MIN_DATE" "$OUTPUT"
-		if [ $? -eq 100 ]; then
-			rm $BINLOG_LIST
-			return 100
-		fi
-	done
-	rm $BINLOG_LIST
+	binlog_do_list_events || return 1
 }
 
 function list_full()
@@ -2067,277 +1954,6 @@ function list_full()
 function list_full_remote()
 {
 	ssh -q -o "StrictHostKeyChecking=no" $LIST_REMOTE_HOST MYSQL_SID=$MYSQL_SID myfreerman -q list full
-}
-
-function list_one_binlog_decoded_prefix_line()
-{
-	return
-}
-
-function list_one_binlog_events()
-{
-	FULL_PATH="$1"
-	MIN_DATE="$2"
-	OUTPUT="$3"
-
-	#if binlog does not exist, just ignore it because probably binlogs were flushed
-	if ! [ -f "$FULL_PATH" ]; then
-		return
-	fi
-
-	#sequence is the last 6 chars in binlog path
-	SEQ=${FULL_PATH:(-6)}
-
-	MARK_LIST=`mktemp /tmp/myfreerman.XXXXXX`
-	if [ -n "$MIN_DATE" ]; then
-		#list only marks
-		mysqlbinlog --defaults-file="$SERVER_CONFIG" --start-datetime="$MIN_DATE" "$FULL_PATH" | grep -Ew 'Table_map|STMT_END_F' >$MARK_LIST
-	else
-		mysqlbinlog --defaults-file="$SERVER_CONFIG" "$FULL_PATH" | grep -Ew 'Table_map|STMT_END_F' >$MARK_LIST
-	fi
-
-	TOTAL_LINES=`wc -l $MARK_LIST | cut -d \  -f 1`
-	#if mark list is empty, inform we are already before min date
-	if [ $TOTAL_LINES -eq 0 ]; then
-		rm $MARK_LIST
-		return 100
-	fi
-
-	#if thread count is greater than 50% of total lines, reduce it
-	HALF_LINES=`expr $TOTAL_LINES / 2`
-	if [ $THREADS -gt $HALF_LINES ]; then
-		THREADS=$HALF_LINES
-	fi
-
-	THREAD_LINE_COUNT=$((TOTAL_LINES/THREADS+1))
-
-	#if thread line count is odd, make it even
-	MOD=$(($THREAD_LINE_COUNT%2))
-	if [ $MOD -eq 1 ]; then
-		THREAD_LINE_COUNT=$((THREAD_LINE_COUNT+1))
-	fi
-
-	START_LINE=1
-	for I in `seq 1 $THREADS`; do
-		list_one_binlog_events_th "$MARK_LIST" $TOTAL_LINES $START_LINE $THREAD_LINE_COUNT "$OUTPUT" &
-		START_LINE=$((START_LINE+THREAD_LINE_COUNT))
-	done
-	wait
-
-	rm $MARK_LIST
-}
-
-function list_one_binlog_events_detailed()
-{
-	FULL_PATH="$1"
-	MIN_DATE="$2"
-	OUTPUT="$3"
-
-	#if binlog does not exist, just ignore it because probably binlogs were flushed
-	if ! [ -f "$FULL_PATH" ]; then
-		return
-	fi
-
-	#sequence is the last 6 chars in binlog path
-	SEQ=${FULL_PATH:(-6)}
-
-	SQL=`mktemp /tmp/myfreerman.XXXXXX`
-	if [ -n "$MIN_DATE" ]; then
-		mysqlbinlog --defaults-file="$SERVER_CONFIG" --start-datetime="$MIN_DATE" --result-file=$SQL "$FULL_PATH" || { rm $SQL; return 1; }
-	else
-		mysqlbinlog --defaults-file="$SERVER_CONFIG" --result-file=$SQL "$FULL_PATH" || { rm $SQL; return 1; }
-	fi
-	SQL_LINE_COUNT=`wc -l $SQL | awk '{ print $1; }'`
-
-	START_CMD_LIST=`mktemp /tmp/myfreerman.XXXXXX`
-	grep -wn ^BINLOG $SQL | cut -d : -f 1 >$START_CMD_LIST
-
-	TOTAL_LINES=`wc -l $START_CMD_LIST | cut -d \  -f 1`
-	#if start list is empty, inform we are already before min date
-	if [ $TOTAL_LINES -eq 0 ]; then
-		rm $MARK_LIST
-		return 100
-	fi
-
-	if [ $THREADS -gt $TOTAL_LINES ]; then
-		THREADS=$TOTAL_LINES
-	fi
-
-	THREAD_LINE_COUNT=$((TOTAL_LINES/THREADS))
-	#if there's gonna be ramining lines in the end, add one
-	MOD=$((TOTAL_LINES%THREADS))
-	if [ $MOD -ne 0 ]; then
-		THREAD_LINE_COUNT=$((THREAD_LINE_COUNT+1))
-	fi
-
-	START_LINE=1
-	for I in `seq 1 $THREADS`; do
-		LOCAL_LIST=`mktemp /tmp/myfreerman.XXXXXX`
-		HEAD=$((START_LINE+THREAD_LINE_COUNT-1))
-		TAIL=$THREAD_LINE_COUNT
-		head -n $HEAD $START_CMD_LIST | tail -n $TAIL >$LOCAL_LIST
-		list_one_binlog_events_detailed_th $SQL $SQL_LINE_COUNT $LOCAL_LIST "$OUTPUT" &
-		START_LINE=$((START_LINE+THREAD_LINE_COUNT))
-	done
-	wait
-
-	rm $SQL $START_CMD_LIST
-}
-
-function list_one_binlog_events_detailed_th()
-{
-	SQL=$1
-	SQL_TOTAL_LINES=$2
-	LOCAL_LIST=$3
-	OUTPUT="$4"
-
-	for LINE in `cat "$LOCAL_LIST"`; do
-		TAIL=$((SQL_TOTAL_LINES-LINE+1))
-		FULL_CMD=`mktemp /tmp/myfreerman.XXXXXX`
-		HEAD=`tail -n $TAIL $SQL | grep -n -m 1 '\;' | cut -d : -f 1`
-		tail -n $TAIL $SQL | head -n $HEAD >$FULL_CMD
-		SIZE=`stat --format=%s $FULL_CMD`
-		#remove LF
-		SIZE=$((SIZE-1))
-		rm $FULL_CMD
-		if [ $SIZE -lt 500 ]; then
-			continue
-		fi
-		if [ "$RMAN_USE_BYTES" == "1" ]; then
-			echo $SIZE
-		else
-			echo scale=1\; $SIZE / 1024 / 1024 | bc -s | sed -e 's/^\./0\./'
-		fi
-	done
-	rm $LOCAL_LIST
-}
-
-function list_one_binlog_events_th()
-{
-	INPUT="$1"
-	TOTAL_LINES=$2
-	START_LINE=$3
-	LINE_COUNT=$4
-	OUTPUT="$5"
-	
-	#if our first line is greater than total number of lines of the file, just ignore it
-	if [ $START_LINE -gt $TOTAL_LINES ]; then
-		return
-	fi
-	MARK_LIST=`mktemp /tmp/myfreerman.XXXXXX`
-	TAIL=$((TOTAL_LINES-START_LINE+1))
-	tail -n $TAIL "$INPUT" | head -n $LINE_COUNT >$MARK_LIST
-
-	#for each line
-	while IFS= read -r LINE; do
-		#if line is a table mapping, save table name and position of the end of the mapping, which is the beginning of the event
-		if [[ "$LINE" =~ .*"Table_map".* ]]; then
-			MAP_END_LOG_POS=`echo $LINE | cut -d \  -f 7`
-			TABLE=`echo $LINE | cut -d \  -f 11 | tr -d \\\``
-			continue
-		fi
-		#if line is STATEMENT END
-		if [ -n "$TABLE" ] && [[ "$LINE" =~ .*"STMT_END_F".* ]]; then
-			STMT_END_LOG_POS=`echo $LINE | cut -d \  -f 7`
-			ENC_SIZE=$((STMT_END_LOG_POS-MAP_END_LOG_POS))
-			SIZE=`scale=0; echo $ENC_SIZE \* 1.4 | bc -s`
-
-			Y="20${LINE:1:2}"
-			M="${LINE:3:2}"
-			D="${LINE:5:2}"
-			DATE="$Y-$M-$D"
-			TIME="${LINE:8:8}"
-			#if hour has only one digit, prepend '0'
-			FIRST_DIGIT="${TIME:0:1}"
-			if [ "$FIRST_DIGIT" == " " ]; then
-				TIME="0${TIME:1:7}"
-			fi
-
-			#operation
-			RAW_OP=`echo $LINE | cut -d \  -f 10`
-			#split op name and uppercate
-			L_OP=`echo $RAW_OP | cut -d _ -f 1`
-			OP=${L_OP^^}
-			#'WRITE' means INSET
-			if [ "$OP" == "WRITE" ]; then
-				OP="INSERT"
-			fi
-
-			SIZE_MB=`echo scale=1\; $SIZE / 1024 / 1024 | bc -s | sed -e 's/^\./0\./'`
-			if [ "$RMAN_USE_BYTES" == "1" ]; then
-				printf "%s %s %s %s %-80s %s\n" $SEQ $DATE $TIME $OP $TABLE $SIZE >>"$OUTPUT"
-			else
-				printf "%s %s %s %s %-80s %s\n" $SEQ $DATE $TIME $OP $TABLE $SIZE_MB >>"$OUTPUT"
-			fi
-			TABLE=
-		fi
-	done <$MARK_LIST
-	rm $MARK_LIST
-}
-
-function list_one_binlog_events_new()
-{
-	FULL_PATH="$1"
-	MIN_DATE="$2"
-	return
-
-	#if binlog does not exist, just ignore it because probably binlogs were flushed
-	if ! [ -f "$FULL_PATH" ]; then
-		return
-	fi
-
-	#sequence is the last 6 chars in binlog path
-	SEQ=${FULL_PATH:(-6)}
-	#create tmp file for sql
-	SQL=`mktemp /tmp/myfreerman.XXXXXX`
-	mysqlbinlog --defaults-file="$SERVER_CONFIG" --start-datetime="$MIN_DATE" --result-file $SQL "$FULL_PATH" || return 1
-
-	#if last event in binlog is earlier than our min date, ignore this binlog and return specific code (100)
-	LAST_TS="`get_binlog_last_event_timestamp $SQL`"
-	if [[ "$LAST_TS" < "$MIN_DATE" ]]; then
-		rm $SQL
-		return 100
-	fi
-
-	FILE_LINES=`wc -l $SQL | cut -d \  -f 1`
-	START_BUFF=`mktemp /tmp/myfreerman.XXXXXX`
-
-	#list all table maps (table_map
-	grep -win table_map $SQL >$START_BUFF
-
-	#for each table map
-	while IFS= read -r MAP_LINE; do
-		MAP_END_LOG_POS=`echo $MAP_LINE | cut -d \  -f 7`
-		TABLE=`echo $MAP_LINE | cut -d \  -f 11`
-		LINE_NUM=`echo $MAP_LINE | cut -d : -f 1`
-		#look forward until 'STMT_END_F' is found
-		TAIL_LINES=$((FILE_LINES-LINE_NUM))
-		#time tail -n $TAIL_LINES $SQL | grep -m 1 -w STMT_END_F
-		END_LINE=`tail -n $TAIL_LINES $SQL | grep -m 1 -w STMT_END_F`
-		STMT_END_LOG_POS=`echo $END_LINE | cut -d \  -f 7`
-		SIZE=$((STMT_END_LOG_POS-MAP_END_LOG_POS))
-
-		Y="20${END_LINE:1:2}"
-		M="${END_LINE:3:2}"
-		D="${END_LINE:5:2}"
-		DATE="$Y-$M-$D"
-		TIME="${END_LINE:8:8}"
-
-		#operation
-		RAW_OP=`echo $END_LINE | cut -d \  -f 10`
-		#split op name and uppercate
-		L_OP=`echo $RAW_OP | cut -d _ -f 1`
-		OP=${L_OP^^}
-		#'WRITE' means INSET
-		if [ "$OP" == "WRITE" ]; then
-			OP="INSERT"
-		fi
-
-		SIZE_MB=`echo scale=2\; $SIZE / 0.74 / 1024 /1024 | bc -s`
-		printf "%s %s %s %-80s %-9s %s\n" $SEQ $DATE $TIME $TABLE $OP $SIZE_MB
-	done <$START_BUFF
-	rm $START_BUFF
-	rm $SQL
 }
 
 function list_remote()
@@ -2362,7 +1978,7 @@ function list_remote()
 function list_server_binlogs()
 {
 	LIST_FILE=`mktemp /tmp/myfreerman.XXXXXX` || return 1
-	mysql --socket="$SERVER_SOCKET" $TARGET_CRED_OPT -e "show binary logs\G" | grep -wi log_name | cut -d \  -f 3 >$LIST_FILE || { remove_lock_file && return 1; }
+	mysql --socket="$SERVER_SOCKET" $TARGET_CRED_OPT_NOPWD -e "show binary logs\G" | grep -wi log_name | cut -d \  -f 3 >$LIST_FILE || { remove_lock_file && return 1; }
 	cat $LIST_FILE
 	rm $LIST_FILE
 }
@@ -2440,6 +2056,15 @@ function mount_target_credentials_opt()
 	fi
 	if [ -n "$DB_PASSWORD" ]; then
 		RESULT="$RESULT --password=$DB_PASSWORD"
+	fi
+	echo -n "$RESULT"
+}
+
+function mount_target_credentials_opt_nopwd()
+{
+	RESULT=
+	if [ -n "$DB_USERNAME" ]; then
+		RESULT="--user=$DB_USERNAME"
 	fi
 	echo -n "$RESULT"
 }
@@ -3622,6 +3247,13 @@ function run()
 	fi
 	SLAVE=0
 	TARGET_CRED_OPT=`mount_target_credentials_opt` || return 1
+	TARGET_CRED_OPT_NOPWD=`mount_target_credentials_opt_nopwd` || return 1
+
+	#if password in config, set env
+	if [ -n "$DB_PASSWORD" ]; then
+		export MYSQL_PWD="$DB_PASSWORD"
+	fi
+
 	MYHOST=`hostname`
 	BINLOG_BACKUP_DIR="$BACKUP_DIR/binlog"
 	RESTORE_BACKUP_DIR="$BACKUP_DIR/restore"
